"""elimino descripcion de expensas

Revision ID: 015867a7b8d7
Revises: ea4c94bfe48a
Create Date: 2026-02-23 18:31:15.728114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015867a7b8d7'
down_revision: Union[str, Sequence[str], None] = 'ea4c94bfe48a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gastos', 'descripcion',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('gastos_categorias', 'descripcion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos_categorias', sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('gastos', 'descripcion',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
