"""Make numero_orden non-nullable in sales

Revision ID: 3cdc1c792e6b
Revises: 644fd2ff4afb
Create Date: 2026-02-11 20:20:26.035133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cdc1c792e6b'
down_revision: Union[str, Sequence[str], None] = '644fd2ff4afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQL Server requires dropping the constraint before modifying nullability
    op.drop_constraint('UQ__Ventas__37067115C0DDA161', 'Ventas', type_='unique')
    
    op.alter_column('Ventas', 'numero_orden',
               existing_type=sa.VARCHAR(length=17, collation='Modern_Spanish_CI_AS'),
               nullable=False)
    
    # Recreate the unique constraint
    op.create_unique_constraint('UQ__Ventas__numero_orden', 'Ventas', ['numero_orden'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UQ__Ventas__numero_orden', 'Ventas', type_='unique')
    
    op.alter_column('Ventas', 'numero_orden',
               existing_type=sa.VARCHAR(length=17, collation='Modern_Spanish_CI_AS'),
               nullable=True)
    
    # Recreate the original constraint
    op.create_unique_constraint('UQ__Ventas__37067115C0DDA161', 'Ventas', ['numero_orden'])
    # ### end Alembic commands ###
