"""Add expense and expense category models

Revision ID: 5b16616d7d8f
Revises: 22f4180cb52e
Create Date: 2026-02-22 19:02:11.418902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b16616d7d8f'
down_revision: Union[str, Sequence[str], None] = '22f4180cb52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos_categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['padre_id'], ['gastos_categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_categorias_id'), 'gastos_categorias', ['id'], unique=False)
    op.create_index(op.f('ix_gastos_categorias_nombre'), 'gastos_categorias', ['nombre'], unique=False)
    op.create_index('ix_gastos_categorias_padre', 'gastos_categorias', ['padre_id'], unique=False)
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_gasto_id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_gasto_id'], ['gastos_categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gastos_categoria', 'gastos', ['categoria_gasto_id'], unique=False)
    op.create_index('ix_gastos_fecha', 'gastos', ['fecha_pago'], unique=False)
    op.create_index(op.f('ix_gastos_id'), 'gastos', ['id'], unique=False)
    op.alter_column('audit_logs', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_gastos_id'), table_name='gastos')
    op.drop_index('ix_gastos_fecha', table_name='gastos')
    op.drop_index('ix_gastos_categoria', table_name='gastos')
    op.drop_table('gastos')
    op.drop_index('ix_gastos_categorias_padre', table_name='gastos_categorias')
    op.drop_index(op.f('ix_gastos_categorias_nombre'), table_name='gastos_categorias')
    op.drop_index(op.f('ix_gastos_categorias_id'), table_name='gastos_categorias')
    op.drop_table('gastos_categorias')
    # ### end Alembic commands ###
