"""agregar campo imagen y fecha_actualizacion a Producto

Revision ID: 837ecfe44461
Revises: 73d7016f8b49
Create Date: 2026-01-14 20:35:21.309847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837ecfe44461'
down_revision: Union[str, Sequence[str], None] = '73d7016f8b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Productos', sa.Column('imagen', sa.String(length=255), nullable=True))
    op.add_column('Productos', sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Productos', 'fecha_actualizacion')
    op.drop_column('Productos', 'imagen')
    # ### end Alembic commands ###
