"""Initial migration

Revision ID: 94182d0f6b12
Revises: 
Create Date: 2026-02-20 20:26:29.225065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94182d0f6b12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Categorias_nombre'), 'Categorias', ['nombre'], unique=True)
    op.create_table('Ofertas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Ofertas_id'), 'Ofertas', ['id'], unique=False)
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Usuarios_email'), 'Usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_Usuarios_username'), 'Usuarios', ['username'], unique=True)
    op.create_table('Ventas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_orden', sa.String(length=17), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_orden')
    )
    op.create_index(op.f('ix_Ventas_fecha_creacion'), 'Ventas', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_Ventas_id'), 'Ventas', ['id'], unique=False)
    op.create_table('order_daily_sequence',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('business_date')
    )
    op.create_table('OfertaItems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['Categorias.id'], ),
    sa.ForeignKeyConstraint(['oferta_id'], ['Ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OfertaItems_id'), 'OfertaItems', ['id'], unique=False)
    op.create_table('Productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['Categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Productos_id'), 'Productos', ['id'], unique=False)
    op.create_index(op.f('ix_Productos_sku'), 'Productos', ['sku'], unique=True)
    op.create_index('ix_productos_categoria', 'Productos', ['categoria_id'], unique=False)
    op.create_table('OfertaItemProductos',
    sa.Column('oferta_item_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oferta_item_id'], ['OfertaItems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['Productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oferta_item_id', 'producto_id')
    )
    op.create_table('ProductoPrecios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['Productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ProductoPrecios_id'), 'ProductoPrecios', ['id'], unique=False)
    op.create_index('ix_productoprecio_producto_cantidad', 'ProductoPrecios', ['producto_id', 'cantidad'], unique=False)
    op.create_table('VentaItems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('oferta_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('producto_sku', sa.String(length=50), nullable=True),
    sa.Column('item_nombre', sa.String(length=255), nullable=False),
    sa.Column('item_categoria', sa.String(length=100), nullable=False),
    sa.Column('item_descripcion', sa.Text(), nullable=True),
    sa.Column('es_pizza_mitad_mitad', sa.Boolean(), nullable=True),
    sa.CheckConstraint('((producto_id IS NOT NULL AND oferta_id IS NULL AND es_pizza_mitad_mitad = 0) OR (producto_id IS NULL AND oferta_id IS NOT NULL AND es_pizza_mitad_mitad = 0) OR (producto_id IS NULL AND oferta_id IS NULL AND es_pizza_mitad_mitad = 1))', name='check_producto_oferta_or_mitad_mitad'),
    sa.ForeignKeyConstraint(['oferta_id'], ['Ofertas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['Productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['Ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_VentaItems_es_pizza_mitad_mitad'), 'VentaItems', ['es_pizza_mitad_mitad'], unique=False)
    op.create_index(op.f('ix_VentaItems_id'), 'VentaItems', ['id'], unique=False)
    op.create_index(op.f('ix_VentaItems_producto_sku'), 'VentaItems', ['producto_sku'], unique=False)
    op.create_index('ix_ventaitems_item_categoria', 'VentaItems', ['item_categoria'], unique=False)
    op.create_index('ix_ventaitems_venta_id', 'VentaItems', ['venta_id'], unique=False)
    op.create_index('ix_ventaitems_venta_oferta', 'VentaItems', ['venta_id', 'oferta_id'], unique=False)
    op.create_index('ix_ventaitems_venta_producto', 'VentaItems', ['venta_id', 'producto_id'], unique=False)
    op.create_table('VentaItemOfertaProductos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venta_item_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('producto_nombre', sa.String(length=50), nullable=False),
    sa.Column('categoria_nombre', sa.String(length=50), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['Productos.id'], ),
    sa.ForeignKeyConstraint(['venta_item_id'], ['VentaItems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_VentaItemOfertaProductos_id'), 'VentaItemOfertaProductos', ['id'], unique=False)
    op.create_index('ix_ventaitemofertaproductos_categoria_nombre', 'VentaItemOfertaProductos', ['categoria_nombre'], unique=False)
    op.create_index('ix_ventaitemofertaproductos_producto_nombre', 'VentaItemOfertaProductos', ['producto_nombre'], unique=False)
    op.create_index('ix_ventaitemofertaproductos_venta_item_id', 'VentaItemOfertaProductos', ['venta_item_id'], unique=False)
    op.create_index('ix_ventaitemofertaproductos_ventaitem_producto', 'VentaItemOfertaProductos', ['venta_item_id', 'producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ventaitemofertaproductos_ventaitem_producto', table_name='VentaItemOfertaProductos')
    op.drop_index('ix_ventaitemofertaproductos_venta_item_id', table_name='VentaItemOfertaProductos')
    op.drop_index('ix_ventaitemofertaproductos_producto_nombre', table_name='VentaItemOfertaProductos')
    op.drop_index('ix_ventaitemofertaproductos_categoria_nombre', table_name='VentaItemOfertaProductos')
    op.drop_index(op.f('ix_VentaItemOfertaProductos_id'), table_name='VentaItemOfertaProductos')
    op.drop_table('VentaItemOfertaProductos')
    op.drop_index('ix_ventaitems_venta_producto', table_name='VentaItems')
    op.drop_index('ix_ventaitems_venta_oferta', table_name='VentaItems')
    op.drop_index('ix_ventaitems_venta_id', table_name='VentaItems')
    op.drop_index('ix_ventaitems_item_categoria', table_name='VentaItems')
    op.drop_index(op.f('ix_VentaItems_producto_sku'), table_name='VentaItems')
    op.drop_index(op.f('ix_VentaItems_id'), table_name='VentaItems')
    op.drop_index(op.f('ix_VentaItems_es_pizza_mitad_mitad'), table_name='VentaItems')
    op.drop_table('VentaItems')
    op.drop_index('ix_productoprecio_producto_cantidad', table_name='ProductoPrecios')
    op.drop_index(op.f('ix_ProductoPrecios_id'), table_name='ProductoPrecios')
    op.drop_table('ProductoPrecios')
    op.drop_table('OfertaItemProductos')
    op.drop_index('ix_productos_categoria', table_name='Productos')
    op.drop_index(op.f('ix_Productos_sku'), table_name='Productos')
    op.drop_index(op.f('ix_Productos_id'), table_name='Productos')
    op.drop_table('Productos')
    op.drop_index(op.f('ix_OfertaItems_id'), table_name='OfertaItems')
    op.drop_table('OfertaItems')
    op.drop_table('order_daily_sequence')
    op.drop_index(op.f('ix_Ventas_id'), table_name='Ventas')
    op.drop_index(op.f('ix_Ventas_fecha_creacion'), table_name='Ventas')
    op.drop_table('Ventas')
    op.drop_index(op.f('ix_Usuarios_username'), table_name='Usuarios')
    op.drop_index(op.f('ix_Usuarios_email'), table_name='Usuarios')
    op.drop_table('Usuarios')
    op.drop_index(op.f('ix_Ofertas_id'), table_name='Ofertas')
    op.drop_table('Ofertas')
    op.drop_index(op.f('ix_Categorias_nombre'), table_name='Categorias')
    op.drop_table('Categorias')
    # ### end Alembic commands ###
