"""Remove descripcion and add activo to Category

Revision ID: e5b7b6df776d
Revises: c1d2e3f4g5h6
Create Date: 2026-02-12 23:15:34.367174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b7b6df776d'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4g5h6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Categorias', sa.Column('activo', sa.Boolean(), nullable=False, server_default='1'))
    op.drop_column('Categorias', 'descripcion')
    op.drop_index(op.f('ix_Usuarios_email'), table_name='Usuarios')
    op.create_index(op.f('ix_Usuarios_email'), 'Usuarios', ['email'], unique=True)
    op.drop_index(op.f('ix_Usuarios_username'), table_name='Usuarios')
    op.create_index(op.f('ix_Usuarios_username'), 'Usuarios', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Usuarios_username'), table_name='Usuarios')
    op.create_index(op.f('ix_Usuarios_username'), 'Usuarios', ['username'], unique=False)
    op.drop_index(op.f('ix_Usuarios_email'), table_name='Usuarios')
    op.create_index(op.f('ix_Usuarios_email'), 'Usuarios', ['email'], unique=False)
    op.add_column('Categorias', sa.Column('descripcion', sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('Categorias', 'activo')
    # ### end Alembic commands ###
