"""Remove proveedor from gastos

Revision ID: ea4c94bfe48a
Revises: 5b16616d7d8f
Create Date: 2026-02-22 19:33:40.885468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4c94bfe48a'
down_revision: Union[str, Sequence[str], None] = '5b16616d7d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gastos', 'proveedor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('proveedor', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
